# Generated by Django 4.1 on 2022-08-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_post_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=models.CharField(max_length=4096),
        ),
    ]
