# Generated by Django 4.1 on 2022-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_alter_post_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sentiment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='symbols',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
