# Generated by Django 4.1 on 2022-08-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_post_sentiment_post_symbols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='symbols',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
