# Generated by Django 4.1 on 2022-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_post_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_path',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
