# Generated by Django 4.1 on 2022-08-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0006_post_images_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
