# Generated by Django 4.1 on 2022-08-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0008_post_image_i'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_i',
            new_name='headshot',
        ),
    ]
