# Generated by Django 4.1 on 2022-08-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_rename_image_i_post_headshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='headshot',
        ),
        migrations.RemoveField(
            model_name='post',
            name='images_path',
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
