# Generated by Django 4.1 on 2022-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_remove_post_headshot_remove_post_images_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images'),
        ),
    ]
